#include "Constants.h"
#include <avr/pgmspace.h>

// PROGMEM stuff - autogenerated with code.export
//
// Must always contain 3 bytes. The first is never used, as address 0 is reserved. The next two are the 
// reference to the static DictionaryHead - copied to RAM on boot
//
// To reset, set size=3 and data {255, 0, 0}

static Word size=121;

static const PROGMEM Byte dataSegmentStatic[]={
  255,0,89
  ,5,112,114,105,109,101,0,3,0,0,17,0,0,33,54,2,2,18,56,19
  ,8,25,3,0,42,6,9,16,54,9,25,3,0,46,6,3,0,21,5,57
  ,57,8,4,57,57,9,4,10,115,112,101,101,100,84,101,115,116,49,0,50
  ,0,0,69,0,9,9,63,3,121,37,128,17,57,64,4,10,115,112,101,101
  ,100,84,101,115,116,50,0,78,0,0,97,0,61,24,63,9,2,13,128,17
  ,57,20,54,3,15,160,21,3,0,118,6,3,0,99,5,57,64,4
};




Word staticDataSize() {
  return size;
}

Byte staticDataRead (Word pos) {
  return pgm_read_byte_near(dataSegmentStatic+pos);
}
