#include "Constants.h"
#include <avr/pgmspace.h>

// PROGMEM stuff - autogenerated 
// Must always contain 3 bytes. The first is never used, as address 0 is reserved. The next two are the 
// reference to the static DictionaryHead - copied to RAM on boot
//

static int size = 3;



static const PROGMEM Byte dataSegmentStatic[] = {255,0,0}; 

Word staticDataSize() {
  return size;
}

Byte staticDataRead (Word pos) {
  return pgm_read_byte_near(dataSegmentStatic+pos);
}
