#include "Constants.h"
#include <avr/pgmspace.h>

// PROGMEM stuff - autogenerated 
// Must always contain 3 bytes. The first is never used, as address 0 is reserved. The next two are the 
// reference to the static DictionaryHead - copied to RAM on boot
//
// To reset, set size=3 and data {255, 0, 0}


static Word size=230;

static const PROGMEM Byte dataSegmentStatic[]={
  255,0,204
  ,7,79,80,95,66,86,65,76,0,3,2,0,2,0,0,7,79,80,95,67
  ,86,65,76,0,18,2,0,3,0,11,6,79,80,95,82,69,84,0,33,2
  ,0,4,0,26,6,79,80,95,74,77,80,0,47,2,0,5,0,40,11,79
  ,80,95,67,79,78,68,95,74,77,80,0,61,2,0,6,0,54,7,79,80
  ,95,66,76,79,66,0,80,2,0,7,0,73,7,79,80,95,90,69,82,79
  ,0,95,2,0,8,0,88,6,79,80,95,79,78,69,0,110,2,0,9,0
  ,103,7,67,72,95,81,85,79,84,0,124,2,0,34,0,117,1,34,0,139
  ,1,0,149,0,132,27,2,7,39,38,59,8,39,8,62,48,2,34,23,3
  ,0,172,6,39,18,3,0,157,5,51,60,46,4,8,66,117,102,67,108,101
  ,97,114,0,176,0,0,193,0,141,4,8,49,46,4,6,66,117,102,65,100
  ,100,0,197,0,0,212,0,185,18,48,48,47,13,18,2,2,53,49,46,49
  ,51,48,47,18,49,46,4
};



Word staticDataSize() {
  return size;
}

Byte staticDataRead (Word pos) {
  return pgm_read_byte_near(dataSegmentStatic+pos);
}
